name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
          - {
            os: macos-latest,
            c: "clang",
            cmake_opts: "-DWANT_PLAYER=ON -DWANT_STATIC=ON -DWANT_OPENAL=ON"
          }
          - {
            os: ubuntu-latest,
            c: "clang",
            cmake_opts: "-DWANT_PLAYER=ON -DWANT_STATIC=ON -DWANT_OPENAL=ON -DWANT_ALSA=ON -DWANT_OSS=ON"
          }
          - {
            os: ubuntu-latest,
            c: "gcc",
            cmake_opts: "-DWANT_PLAYER=ON -DWANT_STATIC=ON -DWANT_OPENAL=ON -DWANT_ALSA=ON -DWANT_OSS=ON"
          }
          - {
            os: windows-latest,
            c: "cl",
            cmake_opts: "-DWANT_PLAYER=ON -DWANT_STATIC=ON -DWANT_WIN32_MM=ON"
          }
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies (Linux)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libopenal-dev
      - name: Install dependencies (macOS)
        if: matrix.config.os == 'macos-latest'
        run: |
          brew install openal-soft
      - name: Build with ${{ matrix.config.os }} / ${{ matrix.config.c }}
        env:
          CC: ${{ matrix.config.c }}
        run: |
          cmake -B build ${{ matrix.config.cmake_opts }} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=out
          cmake --build build -j2
          cmake --install build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wildmidi-${{ matrix.config.os }}-${{ matrix.config.c }}
          path: build/out/
          retention-days: 14
